version: 2
jobs:
  build:
    working_directory: ~/cursor
    docker:
      - image: python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Download and start X
          command: |
            apt-get install -y x11vnc
            x11vnc -forever -nopw
          background: true
      - run: 
          name: "Setup custom environment variables"
          command: echo 'export DISPLAY=":0.0"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      - run:
          name: Run tests
          command: py.test --cov cursor --cov-report html
      - store_artifacts:
          path: htmlcov
workflows:
  version: 2
  workflow:
    jobs:
    - build
